site_name: MyDocs 
copyright: Copyright © 2023 - 2024 siwen

repo_name: siwen-li/docs
repo_url: https://github.com/siwen-li/docs
version: 1.0.0
edit_uri: edit/main/docs/

# 导航 
nav:
  - 标签:
    - index.md 
  - 测试页:
    - test.md 
  - SQL:
    # - MySQL: 
    - Oracle: 
        # - sql/oracle/index.md
        - Oracle 正则表达式: sql/oracle/Oracle_regular_expression.md
        - REGEXP_COUNT 函数: sql/oracle/REGEXP_COUNT.md
        - REGEXP_INSTR 函数: sql/oracle/REGEXP_INSTR.md
        - REGEXP_REPLACE 函数: sql/oracle/REGEXP_REPLACE.md
        - REGEXP_SUBSTR 函数: sql/oracle/REGEXP_SUBSTR.md
        - REGEXP_LIKE 函数: sql/oracle/REGEXP_LIKE.md
        

        - Oracle 层次查询: sql/oracle/Hierarchical_Queries.md
        - Oracle 层次查询运算符: sql/oracle/Hierarchical_Query_Operators.md
        - Oracle 层次查询伪列: sql/oracle/Hierarchical_Query_Pseudocolumns.md
        - SYS_CONNECT_BY_PATH 函数: sql/oracle/SYS_CONNECT_BY_PATH.md  
  - Linux:
    - Linux 正则表达式: linux/Linunx_regular_expression.md
    - grep 命令: linux/grep.md
    - sed 命令: linux/sed.md
    - awk 命令: linux/awk.md
    - awk 编程: linux/awk_programming.md

    
theme:
  name: material
  custom_dir: overrides
  language: zh
  # logo: assets/logo.png
  icon:
    # logo: logo
    repo: fontawesome/brands/github
    edit: material/pencil-box-multiple-outline

  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg

  # icon:
  #   annotation: material/plus-circle
  #   previous: fontawesome/solid/angle-left
  #   next: fontawesome/solid/angle-right

  palette:
    - scheme: default
      primary: white
      # accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      # accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

  features:
    - content.action.edit  # 编辑代码
    - content.action.view
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking   # 锚点跟踪

    # - toc.integrate # 导航集成 

    - navigation.indexes
    

    # 导航栏
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.path
    # 目录锚点跟随
    - toc.follow

    - search.suggest
    - search.highlight  # 搜索高亮
    - search.share
    - navigation.top
    - navigation.footer  # 页脚
    - content.code.copy  # 代码复制按钮
    - content.code.select
    - content.code.annotate
    - content.tabs.link  # 选项卡链接
    - content.tooltips  # 工具提示 
    


extra:
  homepage: https://example.com
  # 社交链接
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/siwen-li

  generator: false


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true  # 高亮
      # auto_title: true  # 显示代码标题
      # linenums: true  # 添加行号
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true



  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all

  - abbr
  - footnotes
  - md_in_html

  - pymdownx.inlinehilite
  - pymdownx.snippets


  - tables

  # 内联代码
  - pymdownx.critic
  - pymdownx.caret

  # 键盘键
  - pymdownx.keys

  # 字符序列转换为相应的符号
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.tilde


  # 图标和表情符号
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


  # 列表
  - def_list

  # 启用告诫
  - admonition
  - pymdownx.details



# js 
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 自定义css
extra_css:
  - stylesheets/extra.css

# 插件
plugins:
  - search  # 搜索
  - glightbox  # 图片缩放
  
  - tags: # 标签
      tags_file: index.md

  


